### ISSUE TITLE
Support for mss550l (switch) and msl420 (bedside light)

### ISSUE THREAD

**Issue by StephaneM60** [mangoose002/Meross2Domoticz#13]
Hi,

This plugin does work very well (here on a Windows installation of Domoticz).

I have two meross devices currently unsupported : a wall switch (mss550l) and a bedside lamp (msl420).

Your script is able to see them and if I edit the RegExp those are working as it should for turning them on and off (I added them to the 1 channel switch devices)

However, the Meross Cloud library is also supporting light devices, so it would be great to handle the light correctly. The only light device I have is this bedlamp and it support color and brightness (it has supported white temp but meross changed that recently)

I would be happy to apply changes and test the device for you (I could do it myself but you may do it way faster than me, as I'm not familiar at all with MQTT)

**Comment by mangoose002** [comment]
I merged your changes.

**Comment by mangoose002** [comment]
Sorry, I was away from this subject for a long time.
I had a look at what you wrote in your fork, it looks very good

You can create a 'Pull request' and I could merge it to the project.

Regards
