### ISSUE TITLE
Can You Add MSS420F to suppoorted list

### ISSUE THREAD

**Issue by big-ted** [mangoose002/Meross2Domoticz#4]
It acts the same as a MSS425

I can add it as a recognised device

if(device.dev.deviceType == "mss310" || device.dev.deviceType == "mss210" || device.dev.deviceType == "mss420f" || device.dev.deviceType.indexOf("mss425") != -1){

but I am unable to to add it to the section that creates the devices

if(device.dev.deviceType.indexOf("mss425") != -1){

**Comment by mangoose002** [comment]
Hi,

Did you try to replace mss425 by just mss42 in both lines, it shoud work for any deviceType from mss420 to mss429.

It this works for you, I will change the code to handle MSS420 as well.

Regards.

**Comment by big-ted** [comment]
Just tested it with MSS42 and both the MSS420 and MS425 are picked up and work.

Didn't think it would be that simple

**Comment by mangoose002** [comment]
OK, I will change the code to implement this. That is a great news.

Regards

**Comment by mangoose002** [comment]
Test webhook

**Comment by mangoose002** [comment]
test webhook

**Comment by mangoose002** [comment]
test webhook!!!

**Comment by mangoose002** [comment]
The code change has been implemented.
I close the issue.
